spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres
    username: postgres.evttzpxrdmuueumtaitv
    password: Cp1318rmabq

    hikari:
      data-source-properties:
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  properties:
    hibernate:
      format_sql: true

server:
  port: 8080

jwt:
  secret: super-chave-secreta-123